# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='customer_Name',
            field=models.CharField(default='Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='customer_Name',
            field=models.CharField(default='Name', max_length=50, null=True),
        ),
    ]
