# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180213_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='customer_Name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='customer_Name',
        ),
    ]
